server_url: "https://headscale.corimb.garden"
listen_addr: "0.0.0.0:8085"
metrics_listen_addr: "127.0.0.1:9090"
database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_challenge_listen_addr: ""
tls_letsencrypt_hostname: ""
metrics_enabled: false
noise:
  private_key_path: /var/lib/headscale/noise_private.key
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
dns:
  magic_dns: false
  override_local_dns: false
